In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('train_yaOffsB.csv')
df.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1

In [149]:
df_t=pd.read_csv('test_pFkWwen.csv')
df_t.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000002                      188          1          1   
1  F00000007                      410          1          1   
2  F00000011                      626          1          0   
3  F00000013                      731          1          0   
4  F00000014                      789          0          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                NaN   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  
0                  0       2  
1                  0       2  
2                  0       2  
3                  0       2  
4                  0       1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 10 columns):
ID                         88858 non-null object
Estimated_Insects_Count    88858 non-null int64
Crop_Type                  88858 non-null int64
Soil_Type                  88858 non-null int64
Pesticide_Use_Category     88858 non-null int64
Number_Doses_Week          88858 non-null int64
Number_Weeks_Used          79858 non-null float64
Number_Weeks_Quit          88858 non-null int64
Season                     88858 non-null int64
Crop_Damage                88858 non-null int64
dtypes: float64(1), int64(8), object(1)
memory usage: 6.8+ MB


In [5]:
df.describe()

Estimated_Insects_Count     Crop_Type     Soil_Type  \
count             88858.000000  88858.000000  88858.000000   
mean               1399.012210      0.284375      0.458417   
std                 849.048781      0.451119      0.498271   
min                 150.000000      0.000000      0.000000   
25%                 731.000000      0.000000      0.000000   
50%                1212.000000      0.000000      0.000000   
75%                1898.000000      1.000000      1.000000   
max                4097.000000      1.000000      1.000000   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
count            88858.000000       88858.000000       79858.000000   
mean                 2.264186          25.849952          28.623970   
std                  0.461772          15.554428          12.391881   
min                  1.000000           0.000000           0.000000   
25%                  2.000000          15.000000          20.000000   
50%                  2.000000          20.000000          28.000000   
75%                  3.000000          40.000000          37.000000   
max                  3.000000          95.000000          67.000000   

       Number_Weeks_Quit        Season   Crop_Damage  
count       88858.000000  88858.000000  88858.000000  
mean            9.589986      1.896959      0.190562  
std             9.900631      0.701322      0.454215  
min             0.000000      1.000000      0.000000  
25%             0.000000      1.000000      0.000000  
50%             7.000000      2.000000      0.000000  
75%            16.000000      2.000000      0.000000  
max            50.000000      3.000000      2.000000

In [6]:
a=df[df['Number_Weeks_Used'].isnull()]

In [7]:
a

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
5      F00000008                      448          0          1   
6      F00000009                      448          0          1   
10     F00000021                     1212          1          0   
17     F00000037                     2401          0          1   
35     F00000076                      257          0          0   
...          ...                      ...        ...        ...   
88786  F00155793                     1785          1          0   
88788  F00155801                     1898          1          0   
88825  F00155882                     2542          1          0   
88833  F00155899                     2687          1          0   
88838  F00155906                     2840          1          0   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
5                           1                  0                NaN   
6                           1                  0                NaN   
10                          1                  0                NaN   
17                          1                  0                NaN   
35                          3                 30                NaN   
...                       ...                ...                ...   
88786                       2                 60                NaN   
88788                       2                 15                NaN   
88825                       2                 10                NaN   
88833                       2                 10                NaN   
88838                       2                 20                NaN   

       Number_Weeks_Quit  Season  Crop_Damage  
5                      0       2            1  
6                      0       2            1  
10                     0       3            0  
17                     0       1            1  
35                     0       2            0  
...                  ...     ...          ...  
88786                 16       2            0  
88788                  3       1            0  
88825                 21       2            0  
88833                 21       2            0  
88838                 13       1            0  

[9000 rows x 10 columns]

In [8]:
a['Crop_Damage'].value_counts()

0    7495
1    1248
2     257
Name: Crop_Damage, dtype: int64

In [9]:
a['Pesticide_Use_Category'].value_counts()

2    6479
3    2424
1      97
Name: Pesticide_Use_Category, dtype: int64

In [10]:
a['Crop_Type'].value_counts()

0    6397
1    2603
Name: Crop_Type, dtype: int64

In [11]:
df['Number_Weeks_Used'].fillna(value=df['Number_Weeks_Used'].mean(),inplace=True)

In [12]:
df['Number_Weeks_Used'].isnull().sum()

0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 10 columns):
ID                         88858 non-null object
Estimated_Insects_Count    88858 non-null int64
Crop_Type                  88858 non-null int64
Soil_Type                  88858 non-null int64
Pesticide_Use_Category     88858 non-null int64
Number_Doses_Week          88858 non-null int64
Number_Weeks_Used          88858 non-null float64
Number_Weeks_Quit          88858 non-null int64
Season                     88858 non-null int64
Crop_Damage                88858 non-null int64
dtypes: float64(1), int64(8), object(1)
memory usage: 6.8+ MB


In [14]:
import xgboost as xgb

In [15]:
xgbc=xgb.XGBClassifier()

In [16]:
X=df.drop(['Crop_Damage','ID'],axis=1)
y=df['Crop_Damage']

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [19]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [20]:
pred_xgbc=xgbc.predict(X_test)

In [21]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [22]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92     24499
           1       0.51      0.21      0.29      4054
           2       0.42      0.01      0.03       771

    accuracy                           0.85     29324
   macro avg       0.60      0.40      0.41     29324
weighted avg       0.80      0.85      0.81     29324



In [23]:
print(accuracy_score(y_test,pred_xgbc))

0.8453485199836311


In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rf = RandomForestClassifier(random_state=42)

In [26]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [27]:
pred_rf=rf.predict(X_test)

In [28]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91     24499
           1       0.39      0.20      0.26      4054
           2       0.15      0.07      0.09       771

    accuracy                           0.82     29324
   macro avg       0.47      0.41      0.42     29324
weighted avg       0.78      0.82      0.80     29324



In [29]:
print(accuracy_score(y_test,pred_rf))

0.8246487518755968


In [30]:
from sklearn.ensemble import AdaBoostClassifier

In [31]:
ada=AdaBoostClassifier(base_estimator=rf)
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                       

In [32]:
pred_ada=ada.predict(X_test)

In [33]:
print(classification_report(y_test,pred_ada))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91     24499
           1       0.38      0.20      0.26      4054
           2       0.14      0.07      0.09       771

    accuracy                           0.82     29324
   macro avg       0.46      0.41      0.42     29324
weighted avg       0.78      0.82      0.80     29324



In [34]:
print(accuracy_score(y_test,pred_ada))

0.8218524075842314


In [35]:
from sklearn.neighbors import KNeighborsClassifier

In [36]:
knn=KNeighborsClassifier()

In [37]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [38]:
pred_knn=knn.predict(X_test)

In [39]:
print("The accuracy of KNeighbors Classifier is ",accuracy_score(y_test,pred_knn))
print("The Confusion Matrix of KNeighbors Classifier is \n \n",confusion_matrix(y_test,pred_knn))
print("\n")
print("The Classification Report of KNeighbors Classifier is \n \n",classification_report(y_test,pred_knn))

The accuracy of KNeighbors Classifier is  0.8223298322193425
The Confusion Matrix of KNeighbors Classifier is 
 
 [[23341  1140    18]
 [ 3263   757    34]
 [  535   220    16]]


The Classification Report of KNeighbors Classifier is 
 
               precision    recall  f1-score   support

           0       0.86      0.95      0.90     24499
           1       0.36      0.19      0.25      4054
           2       0.24      0.02      0.04       771

    accuracy                           0.82     29324
   macro avg       0.48      0.39      0.40     29324
weighted avg       0.77      0.82      0.79     29324



In [40]:
from sklearn.ensemble import GradientBoostingClassifier

In [41]:
gbc=GradientBoostingClassifier()

In [42]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [43]:
gbc.score(X_test,y_test)

0.844189060155504

In [44]:
pred_gbc=gbc.predict(X_test)

In [45]:
print("The accuracy of Gradient Boosting is ",accuracy_score(y_test,pred_gbc))
print("The Confusion Matrix of Gradient Boosting is \n \n",confusion_matrix(y_test,pred_gbc))
print("\n")
print("The Classification Report of Gradient Boosting is \n \n",classification_report(y_test,pred_gbc))

The accuracy of Gradient Boosting is  0.844189060155504
The Confusion Matrix of Gradient Boosting is 
 
 [[24178   319     2]
 [ 3476   574     4]
 [  577   191     3]]


The Classification Report of Gradient Boosting is 
 
               precision    recall  f1-score   support

           0       0.86      0.99      0.92     24499
           1       0.53      0.14      0.22      4054
           2       0.33      0.00      0.01       771

    accuracy                           0.84     29324
   macro avg       0.57      0.38      0.38     29324
weighted avg       0.80      0.84      0.80     29324



In [46]:
from sklearn.tree import DecisionTreeClassifier

In [47]:
dt=DecisionTreeClassifier()

In [48]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [49]:
pred_dt=dt.predict(X_test)

In [50]:
print("The accuracy of Decision Tree Classifier is ",accuracy_score(y_test,pred_dt))
print("The Confusion Matrix of Decision Tree Classifier is \n \n",confusion_matrix(y_test,pred_dt))
print("\n")
print("The Classification Report of DecisionTree Classifier is \n \n",classification_report(y_test,pred_dt))

The accuracy of Decision Tree Classifier is  0.7476469785840949
The Confusion Matrix of Decision Tree Classifier is 
 
 [[20767  3175   557]
 [ 2710  1097   247]
 [  442   269    60]]


The Classification Report of DecisionTree Classifier is 
 
               precision    recall  f1-score   support

           0       0.87      0.85      0.86     24499
           1       0.24      0.27      0.26      4054
           2       0.07      0.08      0.07       771

    accuracy                           0.75     29324
   macro avg       0.39      0.40      0.40     29324
weighted avg       0.76      0.75      0.75     29324



In [51]:
from sklearn.ensemble import BaggingClassifier

In [52]:
bgc=BaggingClassifier(base_estimator=dt)

In [53]:
bgc.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [54]:
bgc.score(X_test,y_test)

0.8137702905469922

In [55]:
pred_bgc=bgc.predict(X_test)

In [56]:
print("The accuracy of Bagging is ",accuracy_score(y_test,pred_bgc))
print("The Confusion Matrix of Bagging is \n \n",confusion_matrix(y_test,pred_bgc))
print("\n")
print("The Classification Report of Bagging is \n \n",classification_report(y_test,pred_bgc))

The accuracy of Bagging is  0.8137702905469922
The Confusion Matrix of Bagging is 
 
 [[22945  1354   200]
 [ 3012   863   179]
 [  477   239    55]]


The Classification Report of Bagging is 
 
               precision    recall  f1-score   support

           0       0.87      0.94      0.90     24499
           1       0.35      0.21      0.27      4054
           2       0.13      0.07      0.09       771

    accuracy                           0.81     29324
   macro avg       0.45      0.41      0.42     29324
weighted avg       0.78      0.81      0.79     29324



In [57]:
from sklearn.ensemble import VotingClassifier

In [58]:
ensemble=[('Decision Tree',dt),('Random Forest',rf),('Bagging',bgc),('Gradient Boosting',gbc),('AdaBoosting',ada),('XGBClassifier',xgbc)]

In [59]:
vc=VotingClassifier(estimators=ensemble)

In [60]:
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('Decision Tree',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_stat

In [61]:
vc.score(X_test,y_test)

0.8345382621743282

In [62]:
pred_vc=vc.predict(X_test)

In [63]:
print(accuracy_score(y_test,pred_vc))

0.8345382621743282


In [64]:
print("The accuracy of Voting Classifier is ",accuracy_score(y_test,pred_vc))
print("The Confusion Matrix of Voting Classifier is \n \n",confusion_matrix(y_test,pred_vc))
print("\n")
print("The Classification Report of Voting Classifier is \n \n",classification_report(y_test,pred_vc))

The accuracy of Voting Classifier is  0.8345382621743282
The Confusion Matrix of Voting Classifier is 
 
 [[23758   649    92]
 [ 3266   677   111]
 [  532   202    37]]


The Classification Report of Voting Classifier is 
 
               precision    recall  f1-score   support

           0       0.86      0.97      0.91     24499
           1       0.44      0.17      0.24      4054
           2       0.15      0.05      0.07       771

    accuracy                           0.83     29324
   macro avg       0.49      0.39      0.41     29324
weighted avg       0.79      0.83      0.80     29324



In [65]:
from sklearn.linear_model import LogisticRegressionCV

In [66]:
lr=LogisticRegressionCV(cv=5,max_iter=10000)

In [67]:
lr.fit(X_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=5, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=10000, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [68]:
# df.head()

In [69]:
pred_lr=lr.predict(X_test)

In [70]:
print(lr.score(X_train,y_train))
print(lr.score(X_test,y_test))

0.8339100346020761
0.8336857181830583


In [71]:
print("The accuracy of Logistic Regression is ",accuracy_score(y_test,pred_lr))
print("The Confusion Matrix of Logistic Regression is \n \n",confusion_matrix(y_test,pred_lr))
print("\n")
print("The Classification Report of Logistic Regression is \n \n",classification_report(y_test,pred_lr))

The accuracy of Logistic Regression is  0.8336857181830583
The Confusion Matrix of Logistic Regression is 
 
 [[24287   212     0]
 [ 3894   160     0]
 [  743    28     0]]


The Classification Report of Logistic Regression is 
 
               precision    recall  f1-score   support

           0       0.84      0.99      0.91     24499
           1       0.40      0.04      0.07      4054
           2       0.00      0.00      0.00       771

    accuracy                           0.83     29324
   macro avg       0.41      0.34      0.33     29324
weighted avg       0.76      0.83      0.77     29324



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [72]:
df.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88858 entries, 0 to 88857
Data columns (total 10 columns):
ID                         88858 non-null object
Estimated_Insects_Count    88858 non-null int64
Crop_Type                  88858 non-null int64
Soil_Type                  88858 non-null int64
Pesticide_Use_Category     88858 non-null int64
Number_Doses_Week          88858 non-null int64
Number_Weeks_Used          88858 non-null float64
Number_Weeks_Quit          88858 non-null int64
Season                     88858 non-null int64
Crop_Damage                88858 non-null int64
dtypes: float64(1), int64(8), object(1)
memory usage: 6.8+ MB


In [74]:
df1=df.copy(deep=True)

In [75]:
df11=pd.get_dummies(df,columns=['Crop_Type','Soil_Type','Pesticide_Use_Category','Season'],drop_first=True)

In [76]:
df11.head()

ID  Estimated_Insects_Count  Number_Doses_Week  Number_Weeks_Used  \
0  F00000001                      188                  0                0.0   
1  F00000003                      209                  0                0.0   
2  F00000004                      257                  0                0.0   
3  F00000005                      257                  0                0.0   
4  F00000006                      342                  0                0.0   

   Number_Weeks_Quit  Crop_Damage  Crop_Type_1  Soil_Type_1  \
0                  0            0            1            0   
1                  0            1            1            0   
2                  0            1            1            0   
3                  0            1            1            1   
4                  0            1            1            0   

   Pesticide_Use_Category_2  Pesticide_Use_Category_3  Season_2  Season_3  
0                         0                         0         0         0  
1                         0                         0         1         0  
2                         0                         0         1         0  
3                         0                         0         1         0  
4                         0                         0         1         0

In [77]:
df11.shape

(88858, 12)

In [78]:
df.shape

(88858, 10)

In [79]:
X=df11.drop(['Crop_Damage','ID'],axis=1)
y=df11['Crop_Damage']

In [80]:
from sklearn.preprocessing import StandardScaler

In [81]:
sc=StandardScaler()

In [82]:
X_sc=pd.DataFrame(sc.fit_transform(X),columns=X.columns)

In [83]:
from sklearn.model_selection import train_test_split

In [84]:
X_train, X_test, y_train, y_test = train_test_split(X_sc, y, test_size=0.33, random_state=42)

In [85]:
lr1=LogisticRegressionCV(cv=3,max_iter=10000)

In [86]:
lr1.fit(X_train,y_train)

LogisticRegressionCV(Cs=10, class_weight=None, cv=3, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=10000, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [87]:
pred_lr1=lr1.predict(X_test)

In [88]:
print(lr1.score(X_train,y_train))
print(lr1.score(X_test,y_test))

0.8391507373937582
0.8376074205429


In [89]:
print("The accuracy of Logistic Regression is ",accuracy_score(y_test,pred_lr1))
print("The Confusion Matrix of Logistic Regression is \n \n",confusion_matrix(y_test,pred_lr1))
print("\n")
print("The Classification Report of Logistic Regression is \n \n",classification_report(y_test,pred_lr1))

The accuracy of Logistic Regression is  0.8376074205429
The Confusion Matrix of Logistic Regression is 
 
 [[24099   400     0]
 [ 3591   463     0]
 [  631   140     0]]


The Classification Report of Logistic Regression is 
 
               precision    recall  f1-score   support

           0       0.85      0.98      0.91     24499
           1       0.46      0.11      0.18      4054
           2       0.00      0.00      0.00       771

    accuracy                           0.84     29324
   macro avg       0.44      0.37      0.37     29324
weighted avg       0.77      0.84      0.79     29324



C:\Users\lenovo\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [90]:
import xgboost as xgb

In [91]:
xgbc=xgb.XGBClassifier()

In [92]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [93]:
pred_xgbc=xgbc.predict(X_test)

In [94]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [95]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92     24499
           1       0.50      0.21      0.29      4054
           2       0.40      0.01      0.02       771

    accuracy                           0.84     29324
   macro avg       0.59      0.40      0.41     29324
weighted avg       0.80      0.84      0.81     29324



In [96]:
print(accuracy_score(y_test,pred_xgbc))

0.8448028918292184


In [97]:
from sklearn.ensemble import RandomForestClassifier

In [98]:
rf = RandomForestClassifier(random_state=42)

In [99]:
rf.fit(X_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=42, verbose=0,
                       warm_start=False)

In [100]:
pred_rf=rf.predict(X_test)

In [101]:
print(classification_report(y_test,pred_rf))

              precision    recall  f1-score   support

           0       0.87      0.95      0.91     24499
           1       0.39      0.20      0.27      4054
           2       0.15      0.07      0.10       771

    accuracy                           0.82     29324
   macro avg       0.47      0.41      0.42     29324
weighted avg       0.78      0.82      0.80     29324



In [102]:
print(accuracy_score(y_test,pred_rf))

0.8245464465966443


In [103]:
from sklearn.ensemble import AdaBoostClassifier

In [104]:
ada=AdaBoostClassifier(base_estimator=rf)
ada.fit(X_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R',
                   base_estimator=RandomForestClassifier(bootstrap=True,
                                                         ccp_alpha=0.0,
                                                         class_weight=None,
                                                         criterion='gini',
                                                         max_depth=None,
                                                         max_features='auto',
                                                         max_leaf_nodes=None,
                                                         max_samples=None,
                                                         min_impurity_decrease=0.0,
                                                         min_impurity_split=None,
                                                         min_samples_leaf=1,
                                                         min_samples_split=2,
                                       

In [105]:
pred_ada=ada.predict(X_test)

In [106]:
print(classification_report(y_test,pred_ada))

              precision    recall  f1-score   support

           0       0.87      0.95      0.90     24499
           1       0.38      0.20      0.26      4054
           2       0.14      0.07      0.09       771

    accuracy                           0.82     29324
   macro avg       0.46      0.41      0.42     29324
weighted avg       0.78      0.82      0.79     29324



In [107]:
print(accuracy_score(y_test,pred_ada))

0.820727049515755


In [108]:
from sklearn.neighbors import KNeighborsClassifier

In [109]:
knn=KNeighborsClassifier()

In [110]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [111]:
pred_knn=knn.predict(X_test)

In [112]:
print("The accuracy of KNeighbors Classifier is ",accuracy_score(y_test,pred_knn))
print("The Confusion Matrix of KNeighbors Classifier is \n \n",confusion_matrix(y_test,pred_knn))
print("\n")
print("The Classification Report of KNeighbors Classifier is \n \n",classification_report(y_test,pred_knn))

The accuracy of KNeighbors Classifier is  0.827820215523121
The Confusion Matrix of KNeighbors Classifier is 
 
 [[23407  1068    24]
 [ 3171   847    36]
 [  513   237    21]]


The Classification Report of KNeighbors Classifier is 
 
               precision    recall  f1-score   support

           0       0.86      0.96      0.91     24499
           1       0.39      0.21      0.27      4054
           2       0.26      0.03      0.05       771

    accuracy                           0.83     29324
   macro avg       0.51      0.40      0.41     29324
weighted avg       0.78      0.83      0.80     29324



In [113]:
from sklearn.ensemble import GradientBoostingClassifier

In [114]:
gbc=GradientBoostingClassifier()

In [115]:
gbc.fit(X_train,y_train)

GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='deprecated',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [116]:
gbc.score(X_test,y_test)

0.8439162460782976

In [117]:
pred_gbc=gbc.predict(X_test)

In [118]:
print("The accuracy of Gradient Boosting is ",accuracy_score(y_test,pred_gbc))
print("The Confusion Matrix of Gradient Boosting is \n \n",confusion_matrix(y_test,pred_gbc))
print("\n")
print("The Classification Report of Gradient Boosting is \n \n",classification_report(y_test,pred_gbc))

The accuracy of Gradient Boosting is  0.8439162460782976
The Confusion Matrix of Gradient Boosting is 
 
 [[24165   331     3]
 [ 3471   582     1]
 [  584   187     0]]


The Classification Report of Gradient Boosting is 
 
               precision    recall  f1-score   support

           0       0.86      0.99      0.92     24499
           1       0.53      0.14      0.23      4054
           2       0.00      0.00      0.00       771

    accuracy                           0.84     29324
   macro avg       0.46      0.38      0.38     29324
weighted avg       0.79      0.84      0.80     29324



In [119]:
from sklearn.tree import DecisionTreeClassifier

In [120]:
dt=DecisionTreeClassifier()

In [121]:
dt.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [122]:
pred_dt=dt.predict(X_test)

In [123]:
print("The accuracy of Decision Tree Classifier is ",accuracy_score(y_test,pred_dt))
print("The Confusion Matrix of Decision Tree Classifier is \n \n",confusion_matrix(y_test,pred_dt))
print("\n")
print("The Classification Report of DecisionTree Classifier is \n \n",classification_report(y_test,pred_dt))

The accuracy of Decision Tree Classifier is  0.7510912563088256
The Confusion Matrix of Decision Tree Classifier is 
 
 [[20836  3117   546]
 [ 2676  1117   261]
 [  441   258    72]]


The Classification Report of DecisionTree Classifier is 
 
               precision    recall  f1-score   support

           0       0.87      0.85      0.86     24499
           1       0.25      0.28      0.26      4054
           2       0.08      0.09      0.09       771

    accuracy                           0.75     29324
   macro avg       0.40      0.41      0.40     29324
weighted avg       0.76      0.75      0.76     29324



In [124]:
from sklearn.ensemble import BaggingClassifier

In [125]:
bgc=BaggingClassifier(base_estimator=dt)

In [126]:
bgc.fit(X_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(ccp_alpha=0.0,
                                                        class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort='deprecated',
                                                        random_state=None,


In [127]:
bgc.score(X_test,y_test)

0.8135315782294367

In [128]:
pred_bgc=bgc.predict(X_test)

In [129]:
print("The accuracy of Bagging is ",accuracy_score(y_test,pred_bgc))
print("The Confusion Matrix of Bagging is \n \n",confusion_matrix(y_test,pred_bgc))
print("\n")
print("The Classification Report of Bagging is \n \n",classification_report(y_test,pred_bgc))

The accuracy of Bagging is  0.8135315782294367
The Confusion Matrix of Bagging is 
 
 [[22927  1385   187]
 [ 3007   873   174]
 [  482   233    56]]


The Classification Report of Bagging is 
 
               precision    recall  f1-score   support

           0       0.87      0.94      0.90     24499
           1       0.35      0.22      0.27      4054
           2       0.13      0.07      0.09       771

    accuracy                           0.81     29324
   macro avg       0.45      0.41      0.42     29324
weighted avg       0.78      0.81      0.79     29324



In [130]:
from sklearn.ensemble import VotingClassifier

In [131]:
ensemble=[('Decision Tree',dt),('Random Forest',rf),('Bagging',bgc),('Gradient Boosting',gbc),('AdaBoosting',ada),('XGBClassifier',xgbc)]

In [132]:
vc=VotingClassifier(estimators=ensemble)

In [133]:
vc.fit(X_train,y_train)

VotingClassifier(estimators=[('Decision Tree',
                              DecisionTreeClassifier(ccp_alpha=0.0,
                                                     class_weight=None,
                                                     criterion='gini',
                                                     max_depth=None,
                                                     max_features=None,
                                                     max_leaf_nodes=None,
                                                     min_impurity_decrease=0.0,
                                                     min_impurity_split=None,
                                                     min_samples_leaf=1,
                                                     min_samples_split=2,
                                                     min_weight_fraction_leaf=0.0,
                                                     presort='deprecated',
                                                     random_stat

In [134]:
vc.score(X_test,y_test)

0.8344700586550265

In [135]:
pred_vc=vc.predict(X_test)

In [136]:
print(accuracy_score(y_test,pred_vc))

0.8344700586550265


In [137]:
print("The accuracy of Voting Classifier is ",accuracy_score(y_test,pred_vc))
print("The Confusion Matrix of Voting Classifier is \n \n",confusion_matrix(y_test,pred_vc))
print("\n")
print("The Classification Report of Voting Classifier is \n \n",classification_report(y_test,pred_vc))

The accuracy of Voting Classifier is  0.8344700586550265
The Confusion Matrix of Voting Classifier is 
 
 [[23769   639    91]
 [ 3284   664   106]
 [  533   201    37]]


The Classification Report of Voting Classifier is 
 
               precision    recall  f1-score   support

           0       0.86      0.97      0.91     24499
           1       0.44      0.16      0.24      4054
           2       0.16      0.05      0.07       771

    accuracy                           0.83     29324
   macro avg       0.49      0.39      0.41     29324
weighted avg       0.79      0.83      0.80     29324



In [138]:
import xgboost as xgb

In [139]:
xgbc=xgb.XGBClassifier()

In [140]:
X=df.drop(['Crop_Damage','ID'],axis=1)
y=df['Crop_Damage']

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [143]:
xgbc.fit(X_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='multi:softprob', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=None, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [144]:
pred_xgbc=xgbc.predict(X_test)

In [145]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix

In [146]:
print(classification_report(y_test,pred_xgbc))

              precision    recall  f1-score   support

           0       0.87      0.98      0.92     24499
           1       0.51      0.21      0.29      4054
           2       0.42      0.01      0.03       771

    accuracy                           0.85     29324
   macro avg       0.60      0.40      0.41     29324
weighted avg       0.80      0.85      0.81     29324



In [147]:
print(accuracy_score(y_test,pred_xgbc))

0.8453485199836311


In [150]:
df_t.head()

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000002                      188          1          1   
1  F00000007                      410          1          1   
2  F00000011                      626          1          0   
3  F00000013                      731          1          0   
4  F00000014                      789          0          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                NaN   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   

   Number_Weeks_Quit  Season  
0                  0       2  
1                  0       2  
2                  0       2  
3                  0       2  
4                  0       1

In [151]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59310 entries, 0 to 59309
Data columns (total 9 columns):
ID                         59310 non-null object
Estimated_Insects_Count    59310 non-null int64
Crop_Type                  59310 non-null int64
Soil_Type                  59310 non-null int64
Pesticide_Use_Category     59310 non-null int64
Number_Doses_Week          59310 non-null int64
Number_Weeks_Used          53417 non-null float64
Number_Weeks_Quit          59310 non-null int64
Season                     59310 non-null int64
dtypes: float64(1), int64(7), object(1)
memory usage: 4.1+ MB


In [152]:
df_t['Number_Weeks_Used'].fillna(value=df_t['Number_Weeks_Used'].mean(),inplace=True)

In [153]:
df_t['Number_Weeks_Used'].isnull().sum()

0

In [154]:
df_t.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59310 entries, 0 to 59309
Data columns (total 9 columns):
ID                         59310 non-null object
Estimated_Insects_Count    59310 non-null int64
Crop_Type                  59310 non-null int64
Soil_Type                  59310 non-null int64
Pesticide_Use_Category     59310 non-null int64
Number_Doses_Week          59310 non-null int64
Number_Weeks_Used          59310 non-null float64
Number_Weeks_Quit          59310 non-null int64
Season                     59310 non-null int64
dtypes: float64(1), int64(7), object(1)
memory usage: 4.1+ MB


In [155]:
b=df_t['ID']

In [156]:
df_t.drop(['ID'],axis=1,inplace=True)

In [157]:
X_test=df_t

In [158]:
new_prediction=xgbc.predict(X_test)

In [159]:
new_prediction

array([1, 1, 1, ..., 1, 0, 0], dtype=int64)

In [160]:
new=df_t

In [161]:
new['ID']=pd.Series(b)

In [162]:
new['Crop_Damage']=pd.Series(new_prediction)

In [163]:
new['Crop_Damage'].value_counts()

0    55902
1     3354
2       54
Name: Crop_Damage, dtype: int64

In [164]:
final=new[['ID','Crop_Damage']]

In [165]:
final

ID  Crop_Damage
0      F00000002            1
1      F00000007            1
2      F00000011            1
3      F00000013            1
4      F00000014            1
...          ...          ...
59305  F00155937            0
59306  F00155940            0
59307  F00155941            1
59308  F00155943            0
59309  F00155944            0

[59310 rows x 2 columns]

In [166]:
final.to_csv (r'C:\Users\lenovo\Desktop\Python\AV-Agri\export_dataframe.csv', index = False)